/**
 * `nextjs-cache-handler` CLI — agent-friendly project setup & diagnostics.
 *
 * Commands:
 *   init   [--yes] [--dry-run] [--skills]  wire the handlers into a Next.js app
 *   doctor [--url <redis-url>]             connectivity + cache-state diagnostics
 *
 * Design constraints:
 *   - Zero dependencies: node builtins only. Redis access reuses the
 *     package's own client adapters (which lazy-load the host app's
 *     installed `redis`/`ioredis` peer).
 *   - Never destructive by default: existing files are left alone unless
 *     `--yes` is passed; next.config changes are shown as instructions.
 *   - Output is written for BOTH humans and agents: stable `[ok]/[warn]/
 *     [action]` prefixes that are trivial to parse.
 */

import fs from "node:fs";
import path from "node:path";

import { buildClient } from "../shared/client/index.js";
import { seedBuildOutput } from "../seed/index.js";
import type { RedisClientLike } from "../types.js";

const OK = "[ok]";
const WARN = "[warn]";
const ACTION = "[action]";
const ERR = "[error]";

interface Ctx {
  cwd: string;
  args: string[];
  flags: Set<string>;
  log: (line: string) => void;
}

// ─── helpers ─────────────────────────────────────────────────────────────────

function readJson(file: string): Record<string, unknown> | null {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8")) as Record<string, unknown>;
  } catch {
    return null;
  }
}

function detectNextMajor(pkg: Record<string, unknown>): {
  raw: string | null;
  major: number | null;
  supportsCacheComponents: boolean;
} {
  const deps = {
    ...(pkg.dependencies as Record<string, string> | undefined),
    ...(pkg.devDependencies as Record<string, string> | undefined),
  };
  const raw = deps["next"] ?? null;
  if (!raw) return { raw: null, major: null, supportsCacheComponents: false };
  const m = raw.match(/(\d+)\.(\d+)/);
  if (!m) return { raw, major: null, supportsCacheComponents: false };
  const major = Number(m[1]);
  const minor = Number(m[2]);
  // cacheHandlers exists from 16.1.5; treat 16.1+ ranges as capable and let
  // the peer range enforce the floor precisely.
  const supportsCacheComponents = major > 16 ? false : major === 16 && minor >= 1;
  return { raw, major, supportsCacheComponents };
}

function detectClient(pkg: Record<string, unknown>): "redis" | "ioredis" | null {
  const deps = {
    ...(pkg.dependencies as Record<string, string> | undefined),
    ...(pkg.devDependencies as Record<string, string> | undefined),
  };
  if (deps["redis"]) return "redis";
  if (deps["ioredis"]) return "ioredis";
  return null;
}

function findNextConfig(cwd: string): string | null {
  for (const name of ["next.config.ts", "next.config.js", "next.config.mjs", "next.config.cjs"]) {
    const p = path.join(cwd, name);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

const RULES_BEGIN = "<!-- nextjs-cache-handler:rules:begin -->";
const RULES_END = "<!-- nextjs-cache-handler:rules:end -->";

function packagedFile(rel: string): string | null {
  // dist/cli/index.cjs|js → package root is two levels up.
  const root = path.resolve(__dirname, "..", "..");
  const p = path.join(root, rel);
  return fs.existsSync(p) ? p : null;
}

function shimSource(kind: "incremental" | "cache-components", clientType: string): string {
  const factory =
    kind === "incremental"
      ? "createIncrementalCacheHandler"
      : "createCacheComponentsHandler";
  const subpath = kind === "incremental" ? "incremental" : "cache-components";
  return `// Generated by \`npx nextjs-cache-handler init\`
const { ${factory} } = require("@leejpsd/nextjs-cache-handler/${subpath}");

module.exports = ${factory}({
  client: { type: "${clientType}", url: process.env.REDIS_URL },
  // Per-deploy namespace isolation — set DEPLOYMENT_VERSION in every runtime
  // environment (Docker: the runner stage), e.g. the git SHA.
  buildNamespace: () => process.env.DEPLOYMENT_VERSION,
});
`;
}

// ─── init ────────────────────────────────────────────────────────────────────

export async function init(ctx: Ctx): Promise<number> {
  const { cwd, flags, log } = ctx;
  const apply = flags.has("--yes") && !flags.has("--dry-run");

  const pkg = readJson(path.join(cwd, "package.json"));
  if (!pkg) {
    log(`${ERR} no package.json in ${cwd} — run inside your Next.js project`);
    return 1;
  }

  const next = detectNextMajor(pkg);
  if (!next.raw) {
    log(`${ERR} "next" is not a dependency here — not a Next.js project`);
    return 1;
  }
  if (next.major !== null && next.major < 15) {
    log(`${ERR} next@${next.raw} unsupported — this package needs next >=15.0.0 <17`);
    return 1;
  }
  log(`${OK} next: ${next.raw} → ${next.supportsCacheComponents ? "BOTH handlers (ISR + 'use cache')" : "ISR handler only"}`);

  const deps = pkg.dependencies as Record<string, string> | undefined;
  if (!deps?.["@leejpsd/nextjs-cache-handler"]) {
    log(`${ACTION} install the package first: npm i @leejpsd/nextjs-cache-handler`);
  } else {
    log(`${OK} @leejpsd/nextjs-cache-handler ${deps["@leejpsd/nextjs-cache-handler"]}`);
  }

  const client = detectClient(pkg);
  if (!client) {
    log(`${ACTION} no Redis client installed — run: npm i redis   (or ioredis for Cluster/Sentinel)`);
  } else {
    log(`${OK} redis client: ${client}`);
  }
  const clientType = client ?? "redis";

  // 1) Wrapper shims.
  const wanted: Array<["incremental" | "cache-components", string]> = [
    ["incremental", "cache-incremental.cjs"],
  ];
  if (next.supportsCacheComponents) wanted.push(["cache-components", "cache-components.cjs"]);

  for (const [kind, file] of wanted) {
    const target = path.join(cwd, file);
    if (fs.existsSync(target)) {
      log(`${OK} ${file} already exists — leaving it untouched`);
      continue;
    }
    if (apply) {
      fs.writeFileSync(target, shimSource(kind, clientType));
      log(`${OK} wrote ${file}`);
    } else {
      log(`${ACTION} would create ${file} (re-run with --yes to write)`);
    }
  }

  // 2) next.config guidance (never auto-edited — users customize this file).
  const cfg = findNextConfig(cwd);
  const cfgLines = [
    `cacheHandler: require.resolve("./cache-incremental.cjs"),`,
    ...(next.supportsCacheComponents
      ? [
          `cacheHandlers: { default: require.resolve("./cache-components.cjs") },`,
          `cacheComponents: true,`,
        ]
      : []),
    `cacheMaxMemorySize: 0, // required for multi-instance correctness`,
  ];
  if (!cfg) {
    log(`${WARN} no next.config found — create one with:`);
  } else {
    const body = fs.readFileSync(cfg, "utf8");
    if (body.includes("cacheHandler")) {
      log(`${OK} ${path.basename(cfg)} already references a cacheHandler — verify it points at the shims above`);
    } else {
      log(`${ACTION} add to ${path.basename(cfg)}:`);
    }
    if (cfg.endsWith(".mjs")) {
      log(`${WARN} ESM config: add  import { createRequire } from "module"; const require = createRequire(import.meta.url);`);
    }
  }
  for (const l of cfgLines) log(`    ${l}`);

  // 3) Env template.
  const envExample = path.join(cwd, ".env.example");
  const envBlock = `\n# @leejpsd/nextjs-cache-handler\nREDIS_URL=redis://127.0.0.1:6379\nDEPLOYMENT_VERSION=dev\n`;
  if (fs.existsSync(envExample)) {
    const body = fs.readFileSync(envExample, "utf8");
    if (body.includes("REDIS_URL")) {
      log(`${OK} .env.example already mentions REDIS_URL`);
    } else if (apply) {
      fs.appendFileSync(envExample, envBlock);
      log(`${OK} appended REDIS_URL / DEPLOYMENT_VERSION to .env.example`);
    } else {
      log(`${ACTION} would append REDIS_URL / DEPLOYMENT_VERSION to .env.example`);
    }
  } else {
    log(`${ACTION} set REDIS_URL and DEPLOYMENT_VERSION in every runtime environment`);
  }

  // 4) Agent rules injection (idempotent via markers).
  const rulesSrc = packagedFile("rules/nextjs-cache-rules.md");
  const ruleTargets = ["CLAUDE.md", "AGENTS.md"]
    .map((f) => path.join(cwd, f))
    .filter((p) => fs.existsSync(p));
  if (rulesSrc && ruleTargets.length > 0) {
    const rules = `\n${RULES_BEGIN}\n${fs.readFileSync(rulesSrc, "utf8")}\n${RULES_END}\n`;
    for (const target of ruleTargets) {
      const body = fs.readFileSync(target, "utf8");
      if (body.includes(RULES_BEGIN)) {
        log(`${OK} ${path.basename(target)} already has the cache rules block`);
      } else if (apply) {
        fs.appendFileSync(target, rules);
        log(`${OK} appended cache rules to ${path.basename(target)}`);
      } else {
        log(`${ACTION} would append cache rules to ${path.basename(target)}`);
      }
    }
  } else if (ruleTargets.length === 0) {
    log(`${WARN} no CLAUDE.md/AGENTS.md found — skip rules injection (create one to guide your agent)`);
  }

  // 5) MCP registration — one file turns any MCP-capable agent (Claude
  // Code, Cursor, ...) into a cache operator via npx (no install needed).
  const mcpPath = path.join(cwd, ".mcp.json");
  if (fs.existsSync(mcpPath)) {
    const body = fs.readFileSync(mcpPath, "utf8");
    if (body.includes("nextjs-cache-handler-mcp")) {
      log(`${OK} .mcp.json already registers the cache MCP server`);
    } else {
      log(`${ACTION} .mcp.json exists — add the "nextjs-cache" server manually (see @leejpsd/nextjs-cache-handler-mcp README)`);
    }
  } else if (apply) {
    fs.writeFileSync(
      mcpPath,
      JSON.stringify(
        {
          mcpServers: {
            "nextjs-cache": {
              command: "npx",
              args: ["-y", "@leejpsd/nextjs-cache-handler-mcp"],
              env: {
                REDIS_URL: "redis://127.0.0.1:6379",
                DEPLOYMENT_VERSION: "dev",
              },
            },
          },
        },
        null,
        2
      ) + "\n"
    );
    log(`${OK} wrote .mcp.json — your agent now has cache_health/tag_state/... tools (edit REDIS_URL for real environments)`);
  } else {
    log(`${ACTION} would create .mcp.json registering @leejpsd/nextjs-cache-handler-mcp`);
  }

  // 6) Optional skill install.
  if (flags.has("--skills")) {
    const skillSrc = packagedFile("skills/nextjs-redis-cache/SKILL.md");
    if (skillSrc) {
      const dest = path.join(cwd, ".claude", "skills", "nextjs-redis-cache", "SKILL.md");
      if (apply) {
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.copyFileSync(skillSrc, dest);
        log(`${OK} installed skill to .claude/skills/nextjs-redis-cache/`);
      } else {
        log(`${ACTION} would install skill to .claude/skills/nextjs-redis-cache/`);
      }
    }
  }

  log(`${OK} init ${apply ? "complete" : "preview complete — re-run with --yes to apply"}. Verify with: npx nextjs-cache-handler doctor`);
  return 0;
}

// ─── doctor ──────────────────────────────────────────────────────────────────

export async function doctor(ctx: Ctx): Promise<number> {
  const { args, log } = ctx;
  const urlIdx = args.indexOf("--url");
  const url = urlIdx >= 0 ? args[urlIdx + 1] : process.env.REDIS_URL;
  if (!url) {
    log(`${ERR} no Redis URL — pass --url <redis-url> or set REDIS_URL`);
    return 1;
  }

  const deployment = process.env.DEPLOYMENT_VERSION;
  log(deployment ? `${OK} DEPLOYMENT_VERSION=${deployment}` : `${WARN} DEPLOYMENT_VERSION not set — keys will use the "unversioned" namespace`);

  let client: RedisClientLike;
  try {
    // Prefer node-redis; fall back to ioredis when only that peer is installed.
    try {
      client = await buildClient({ type: "redis", url });
    } catch (err) {
      if (/Cannot find module/.test((err as Error).message)) {
        client = await buildClient({ type: "ioredis", url });
      } else {
        throw err;
      }
    }
    if (!client.isOpen) await client.connect();
  } catch (err) {
    log(`${ERR} connect failed: ${(err as Error).message}`);
    log(`${ACTION} check the URL/network, or install a client: npm i redis  (or ioredis)`);
    return 1;
  }

  try {
    const t0 = Date.now();
    await client.ping();
    log(`${OK} redis PING ${Date.now() - t0}ms (${url.replace(/\/\/[^@]*@/, "//***@")})`);

    const counts = new Map<string, number>();
    for await (const chunk of client.scanIterator({ MATCH: "next-*", COUNT: 500 })) {
      const keys = Array.isArray(chunk) ? chunk : [chunk];
      for (const k of keys) {
        const key = String(k);
        const m = key.match(/^(next-cache|next-incremental):([a-z-]+):/);
        const bucket = m ? `${m[1]}:${m[2]}` : "other";
        counts.set(bucket, (counts.get(bucket) ?? 0) + 1);
      }
    }
    if (counts.size === 0) {
      log(`${WARN} no next-* keys found — cache not yet exercised (or a custom keyPrefix is in use)`);
    } else {
      for (const [bucket, n] of [...counts.entries()].sort()) {
        log(`${OK} ${bucket}* — ${n} keys`);
      }
    }

    // Round-trip probe in an isolated namespace.
    const probeKey = `next-cache:doctor:${Date.now()}`;
    await client.set(probeKey, "ok", { EX: 30 });
    const back = await client.get(probeKey);
    await client.del(probeKey);
    log(back === "ok" ? `${OK} write/read round-trip` : `${ERR} round-trip failed`);
    return back === "ok" ? 0 : 1;
  } finally {
    client.dispose?.();
  }
}


// ─── seed ────────────────────────────────────────────────────────────────────

export async function seed(ctx: Ctx): Promise<number> {
  const { args, flags, log } = ctx;
  const urlIdx = args.indexOf("--url");
  const url = urlIdx >= 0 ? args[urlIdx + 1] : process.env.REDIS_URL;
  if (!url) {
    log(`${ERR} no Redis URL — pass --url <redis-url> or set REDIS_URL`);
    return 1;
  }
  const flagVal = (name: string): string | undefined => {
    const i = args.indexOf(name);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const dir = flagVal("--dir") ?? ".next";
  const keyPrefix = flagVal("--key-prefix");
  const namespace = flagVal("--namespace");
  const compression = flagVal("--compression") as "gzip" | "brotli" | undefined;
  const hashTag = flags.has("--hash-tag");

  const ns =
    namespace ??
    process.env.DEPLOYMENT_VERSION ??
    process.env.GIT_HASH ??
    "unversioned";
  if (ns === "unversioned") {
    log(`${WARN} no namespace — seeding into "unversioned" (set DEPLOYMENT_VERSION or pass --namespace)`);
  }
  // Print the exact key shape so a config mismatch with the runtime handler
  // (custom keyPrefix / hashTag) is visible instead of silently seeding
  // keys the app never reads.
  log(`${OK} target keys: ${keyPrefix ?? "next-incremental:"}entry:${hashTag ? `{${ns}}` : ns}:*`);

  const seedOpts = {
    dir,
    buildNamespace: ns,
    ...(keyPrefix ? { keyPrefix } : {}),
    ...(compression ? { compression } : {}),
    ...(hashTag ? { hashTag: true } : {}),
  };
  const report = (summary: Awaited<ReturnType<typeof seedBuildOutput>>): number => {
    log(`${OK} seeded: ${summary.routes} app routes, ${summary.pages} pages routes, ${summary.fetch} fetch entries`);
    if (summary.skippedExisting > 0)
      log(`${OK} left ${summary.skippedExisting} newer live entries untouched (NX)`);
    if (summary.skippedRouteHandlers > 0)
      log(`${OK} ${summary.skippedRouteHandlers} prerendered route handlers not seeded (by design)`);
    if (summary.skippedIncomplete > 0)
      log(`${WARN} skipped ${summary.skippedIncomplete} routes (incomplete files or PPR resume state)`);
    for (const e of summary.errors.slice(0, 5)) log(`${WARN} ${e}`);
    return summary.errors.length > 0 ? 1 : 0;
  };

  try {
    return report(
      await seedBuildOutput({ client: { type: "redis", url }, ...seedOpts })
    );
  } catch (err) {
    const msg = (err as Error).message;
    if (/Cannot find module 'redis'/.test(msg)) {
      // Retry with ioredis when only that peer is installed.
      try {
        return report(
          await seedBuildOutput({ client: { type: "ioredis", url }, ...seedOpts })
        );
      } catch (err2) {
        log(`${ERR} ${(err2 as Error).message}`);
        return 1;
      }
    }
    log(`${ERR} ${msg}`);
    return 1;
  }
}

// ─── entry ───────────────────────────────────────────────────────────────────

export async function main(argv: string[] = process.argv.slice(2)): Promise<number> {
  const [cmd, ...rest] = argv;
  const ctx: Ctx = {
    cwd: process.cwd(),
    args: rest,
    flags: new Set(rest.filter((a) => a.startsWith("--"))),
    log: (l) => console.log(l),
  };
  switch (cmd) {
    case "init":
      return init(ctx);
    case "doctor":
      return doctor(ctx);
    case "seed":
      return seed(ctx);
    default:
      console.log(`nextjs-cache-handler <command>

Commands:
  init    [--yes] [--dry-run] [--skills]   wire handlers into this Next.js app
  doctor  [--url <redis-url>]              connectivity + cache diagnostics
  seed    [--dir .next] [--url <u>] [--namespace <ns>] [--key-prefix <p>] [--hash-tag] [--compression gzip|brotli]
          seed prerendered build output into Redis

Agent setup instructions:
  https://raw.githubusercontent.com/leejpsd/nextjs-cache-handler/main/setup-instructions/setup.md`);
      return cmd ? 1 : 0;
  }
}
